name: f86
description: "f86"
version: 0.0.1
homepage:

environment:
  sdk: '>=3.2.0-231.0.dev <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.18.0
  date_format: ^2.0.7
  flutter:
    sdk: flutter
  logger: ^2.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
