/// 指令集
enum CpuInstructionSet {
  // 未知
  unknown('UNKNOWN'),
  // 未使用
  unused('unused'),
  // 前缀
  prefix('PREFIX'),
  add('ADD'),
  push('PUSH'),
  pop('POP'),
  or('OR'),
  adc('ADC'),
  sbb('SBB'),
  and('AND'),
  daa('DAA'),
  sub('SUB'),
  das('DAS'),
  xor('XOR'),
  aaa('AAA'),
  cmp('CMP'),
  aas('AAS'),
  inc('INC'),
  dec('DEC'),
  jo('JO'),
  jno('JNO'),
  jb('JB'),
  jnb('JNB'),
  jz('JZ'),
  jnz('JNZ'),
  jbe('JBE'),
  ja('JA'),
  js('JS'),
  jns('JNS'),
  jpe('JPE'),
  jpo('JPO'),
  jl('JL'),
  jge('JGE'),
  jle('JLE'),
  jg('JG'),
  test('TEST'),
  xchg('XCHG'),
  mov('MOV'),
  lea('LEA'),
  nop('NOP'),
  cbw('CBW'),
  cwd('CWD'),
  call('CALL'),
  wait('WAIT'),
  pushf('PUSHF'),
  popf('POPF'),
  sahf('SAHF'),
  lahf('LAHF'),
  movs('MOVS'),
  cmps('CMPS'),
  stos('STOS'),
  lods('LODS'),
  scas('SCAS'),
  ret('RET'),
  les('LES'),
  lds('LDS'),
  int('INT'),
  into('INTO'),
  iret('IRET'),
  rol('ROL'),
  ror('ROR'),
  rcl('RCL'),
  rcr('RCR'),
  shl('SHL'),
  shr('SHR'),
  sar('SAR'),
  aam('AAM'),
  aad('AAD'),
  xlat('XLAT'),
  loopnz('LOOPNZ'),
  loopz('LOOPZ'),
  loop('LOOP'),
  jcxz('JCXZ'),
  inOp('IN'),
  out('OUT'),
  jmp('JMP'),
  repnz('REPNZ'),
  repz('REPZ'),
  hlt('HLT'),
  cmc('CMC'),
  not('NOT'),
  neg('NEG'),
  mul('MUL'),
  imul('IMUL'),
  div('DIV'),
  idiv('IDIV'),
  clc('CLC'),
  stc('STC'),
  cli('CLI'),
  sti('STI'),
  cld('CLD'),
  std('STD'),
  _r('_R');

  final String name;

  const CpuInstructionSet(this.name);
}

/// 操作码
class CpuOpCode {
  /// 指令码
  final int code;

  /// 子code
  final int? subCode;

  /// 指令
  final CpuInstructionSet op;

  CpuOpCode({
    required this.code,
    this.subCode,
    required this.op,
  });
}

/// 操作码指令集
///
/// | 操作码 | mod reg r/m | 偏移量 | 立即数 |
/// | :---: | :---------: | :---: | :---: |
/// | 1B-2B | 2b  3b  3b  | 0B-2B | 0B-2B |
///
/// * 前缀
/// * 操作码: 1111 11(D)(W)
///   * D: 0-reg是源操作数,1-reg
///   * W: 0-数据是Byte,1-数据是Word
/// * 寻址方式: mod(2b) reg(3b) r/m(2b)
///   * mod(2b): 区分另一个操作数在寄存器还是存储器
///   * reg(3b): 寄存器编号
///   * r/m(3b): mod=11B时是寄存器编号,其它时候是存储器寻址
/// * reg与W标志位的关系
/// | reg | W=1 | W=0 |
/// | :-: | :-: | :-: |
/// | 000 | AX  | AL  |
/// | 001 | CX  | CL  |
/// | 010 | DX  | DL  |
/// | 011 | BX  | BL  |
/// | 100 | SP  | AH  |
/// | 101 | BP  | CH  |
/// | 110 | SI  | DH  |
/// | 111 | DI  | BH  |
/// * mod
/// | mod | 寻址方式             |
/// | :-: | :----------------: |
/// | 00  | 存储器寻址           |
/// | 01  | 存储器寻址,8bit偏移   |
/// | 10  | 存储器寻址,16bit偏移  |
/// | 11  | 寄存器寻址           |
/// * r/m
/// | r/m | mod=01:disp8 mod=10:disp16  | mod=11 W=0 | mod=11 W=1 |
/// | 000 | DS:[BX+SI+disp]             | AL         | AX         |
/// | 001 | DS:[BX+DI+disp]             | CL         | CX         |
/// | 010 | SS:[BP+SI+disp]             | DL         | DX         |
/// | 011 | SS:[BP+DI+disp]             | BL         | BX         |
/// | 100 | DS:[SI+disp]                | AH         | SP         |
/// | 101 | DS:[DI+disp]                | CH         | BP         |
/// | 110 | (mod=00 DS:[disp16]) SS:[BP+disp] | DH   | SI         |
/// | 111 | DS:[BX+dip]                 | BH         | DI         |
class CpuInstructionSets {
  /// 获取指令
  static CpuOpCode? getOp(int code, int subCode) {
    var result = _codeTable[code];
    if (result is List) {
      result = result[subCode & 0x07];
    }
    return result as CpuOpCode?;
  }

  static final _codeTable = _generateCodeTable();

  static List _generateCodeTable() {
    final list = List<dynamic>.filled(0x100, null);
    for (final code in _codes) {
      final subCode = code.subCode;
      if (subCode == null) {
        list[code.code] = code;
      } else {
        list[code.code] ??= List<dynamic>.filled(0x08, null);
        list[code.code]?[subCode] = code;
      }
    }
    return list;
  }

  static final _codes = [
    CpuOpCode(code: 0x00, op: CpuInstructionSet.add),
    CpuOpCode(code: 0x01, op: CpuInstructionSet.add),
    CpuOpCode(code: 0x02, op: CpuInstructionSet.add),
    CpuOpCode(code: 0x03, op: CpuInstructionSet.add),
    CpuOpCode(code: 0x04, op: CpuInstructionSet.add),
    CpuOpCode(code: 0x05, op: CpuInstructionSet.add),
    CpuOpCode(code: 0x06, op: CpuInstructionSet.push),
    CpuOpCode(code: 0x07, op: CpuInstructionSet.pop),
    CpuOpCode(code: 0x08, op: CpuInstructionSet.or),
    CpuOpCode(code: 0x09, op: CpuInstructionSet.or),
    CpuOpCode(code: 0x0A, op: CpuInstructionSet.or),
    CpuOpCode(code: 0x0B, op: CpuInstructionSet.or),
    CpuOpCode(code: 0x0C, op: CpuInstructionSet.or),
    CpuOpCode(code: 0x0D, op: CpuInstructionSet.or),
    CpuOpCode(code: 0x0E, op: CpuInstructionSet.push),
    // CpuOpCode(code: 0x0F, op: CpuInstructionSet.unused),
    CpuOpCode(code: 0x10, op: CpuInstructionSet.adc),
    CpuOpCode(code: 0x11, op: CpuInstructionSet.adc),
    CpuOpCode(code: 0x12, op: CpuInstructionSet.adc),
    CpuOpCode(code: 0x13, op: CpuInstructionSet.adc),
    CpuOpCode(code: 0x14, op: CpuInstructionSet.adc),
    CpuOpCode(code: 0x15, op: CpuInstructionSet.adc),
    CpuOpCode(code: 0x16, op: CpuInstructionSet.push),
    CpuOpCode(code: 0x17, op: CpuInstructionSet.pop),
    CpuOpCode(code: 0x18, op: CpuInstructionSet.sbb),
    CpuOpCode(code: 0x19, op: CpuInstructionSet.sbb),
    CpuOpCode(code: 0x1A, op: CpuInstructionSet.sbb),
    CpuOpCode(code: 0x1B, op: CpuInstructionSet.sbb),
    CpuOpCode(code: 0x1C, op: CpuInstructionSet.sbb),
    CpuOpCode(code: 0x1D, op: CpuInstructionSet.sbb),
    CpuOpCode(code: 0x1E, op: CpuInstructionSet.push),
    CpuOpCode(code: 0x1F, op: CpuInstructionSet.pop),
    CpuOpCode(code: 0x20, op: CpuInstructionSet.and),
    CpuOpCode(code: 0x21, op: CpuInstructionSet.and),
    CpuOpCode(code: 0x22, op: CpuInstructionSet.and),
    CpuOpCode(code: 0x23, op: CpuInstructionSet.and),
    CpuOpCode(code: 0x24, op: CpuInstructionSet.and),
    CpuOpCode(code: 0x25, op: CpuInstructionSet.and),
    CpuOpCode(code: 0x26, op: CpuInstructionSet.prefix),
    CpuOpCode(code: 0x27, op: CpuInstructionSet.daa),
    CpuOpCode(code: 0x28, op: CpuInstructionSet.sub),
    CpuOpCode(code: 0x29, op: CpuInstructionSet.sub),
    CpuOpCode(code: 0x2A, op: CpuInstructionSet.sub),
    CpuOpCode(code: 0x2B, op: CpuInstructionSet.sub),
    CpuOpCode(code: 0x2C, op: CpuInstructionSet.sub),
    CpuOpCode(code: 0x2D, op: CpuInstructionSet.sub),
    CpuOpCode(code: 0x2E, op: CpuInstructionSet.prefix),
    CpuOpCode(code: 0x2F, op: CpuInstructionSet.das),
    CpuOpCode(code: 0x30, op: CpuInstructionSet.xor),
    CpuOpCode(code: 0x31, op: CpuInstructionSet.xor),
    CpuOpCode(code: 0x32, op: CpuInstructionSet.xor),
    CpuOpCode(code: 0x33, op: CpuInstructionSet.xor),
    CpuOpCode(code: 0x34, op: CpuInstructionSet.xor),
    CpuOpCode(code: 0x35, op: CpuInstructionSet.xor),
    CpuOpCode(code: 0x36, op: CpuInstructionSet.prefix),
    CpuOpCode(code: 0x37, op: CpuInstructionSet.aaa),
    CpuOpCode(code: 0x38, op: CpuInstructionSet.cmp),
    CpuOpCode(code: 0x39, op: CpuInstructionSet.cmp),
    CpuOpCode(code: 0x3A, op: CpuInstructionSet.cmp),
    CpuOpCode(code: 0x3B, op: CpuInstructionSet.cmp),
    CpuOpCode(code: 0x3C, op: CpuInstructionSet.cmp),
    CpuOpCode(code: 0x3D, op: CpuInstructionSet.cmp),
    CpuOpCode(code: 0x3E, op: CpuInstructionSet.prefix),
    CpuOpCode(code: 0x3F, op: CpuInstructionSet.aas),
    CpuOpCode(code: 0x40, op: CpuInstructionSet.inc),
    CpuOpCode(code: 0x41, op: CpuInstructionSet.inc),
    CpuOpCode(code: 0x42, op: CpuInstructionSet.inc),
    CpuOpCode(code: 0x43, op: CpuInstructionSet.inc),
    CpuOpCode(code: 0x44, op: CpuInstructionSet.inc),
    CpuOpCode(code: 0x45, op: CpuInstructionSet.inc),
    CpuOpCode(code: 0x46, op: CpuInstructionSet.inc),
    CpuOpCode(code: 0x47, op: CpuInstructionSet.inc),
    CpuOpCode(code: 0x48, op: CpuInstructionSet.dec),
    CpuOpCode(code: 0x49, op: CpuInstructionSet.dec),
    CpuOpCode(code: 0x4A, op: CpuInstructionSet.dec),
    CpuOpCode(code: 0x4B, op: CpuInstructionSet.dec),
    CpuOpCode(code: 0x4C, op: CpuInstructionSet.dec),
    CpuOpCode(code: 0x4D, op: CpuInstructionSet.dec),
    CpuOpCode(code: 0x4E, op: CpuInstructionSet.dec),
    CpuOpCode(code: 0x4F, op: CpuInstructionSet.dec),
    CpuOpCode(code: 0x50, op: CpuInstructionSet.push),
    CpuOpCode(code: 0x51, op: CpuInstructionSet.push),
    CpuOpCode(code: 0x52, op: CpuInstructionSet.push),
    CpuOpCode(code: 0x53, op: CpuInstructionSet.push),
    CpuOpCode(code: 0x54, op: CpuInstructionSet.push),
    CpuOpCode(code: 0x55, op: CpuInstructionSet.push),
    CpuOpCode(code: 0x56, op: CpuInstructionSet.push),
    CpuOpCode(code: 0x57, op: CpuInstructionSet.push),
    CpuOpCode(code: 0x58, op: CpuInstructionSet.pop),
    CpuOpCode(code: 0x59, op: CpuInstructionSet.pop),
    CpuOpCode(code: 0x5A, op: CpuInstructionSet.pop),
    CpuOpCode(code: 0x5B, op: CpuInstructionSet.pop),
    CpuOpCode(code: 0x5C, op: CpuInstructionSet.pop),
    CpuOpCode(code: 0x5D, op: CpuInstructionSet.pop),
    CpuOpCode(code: 0x5E, op: CpuInstructionSet.pop),
    CpuOpCode(code: 0x5F, op: CpuInstructionSet.pop),
    // CpuOpCode(code: 0x60, op: CpuInstructionSet.unused),
    // CpuOpCode(code: 0x61, op: CpuInstructionSet.unused),
    // CpuOpCode(code: 0x62, op: CpuInstructionSet.unused),
    // CpuOpCode(code: 0x63, op: CpuInstructionSet.unused),
    // CpuOpCode(code: 0x64, op: CpuInstructionSet.unused),
    // CpuOpCode(code: 0x65, op: CpuInstructionSet.unused),
    // CpuOpCode(code: 0x66, op: CpuInstructionSet.unused),
    // CpuOpCode(code: 0x67, op: CpuInstructionSet.unused),
    // CpuOpCode(code: 0x68, op: CpuInstructionSet.unused),
    // CpuOpCode(code: 0x69, op: CpuInstructionSet.unused),
    // CpuOpCode(code: 0x6A, op: CpuInstructionSet.unused),
    // CpuOpCode(code: 0x6B, op: CpuInstructionSet.unused),
    // CpuOpCode(code: 0x6C, op: CpuInstructionSet.unused),
    // CpuOpCode(code: 0x6D, op: CpuInstructionSet.unused),
    // CpuOpCode(code: 0x6E, op: CpuInstructionSet.unused),
    // CpuOpCode(code: 0x6F, op: CpuInstructionSet.unused),
    CpuOpCode(code: 0x70, op: CpuInstructionSet.jo),
    CpuOpCode(code: 0x71, op: CpuInstructionSet.jno),
    CpuOpCode(code: 0x72, op: CpuInstructionSet.jb),
    CpuOpCode(code: 0x73, op: CpuInstructionSet.jnb),
    CpuOpCode(code: 0x74, op: CpuInstructionSet.jz),
    CpuOpCode(code: 0x75, op: CpuInstructionSet.jnz),
    CpuOpCode(code: 0x76, op: CpuInstructionSet.jbe),
    CpuOpCode(code: 0x77, op: CpuInstructionSet.ja),
    CpuOpCode(code: 0x78, op: CpuInstructionSet.js),
    CpuOpCode(code: 0x79, op: CpuInstructionSet.jns),
    CpuOpCode(code: 0x7A, op: CpuInstructionSet.jpe),
    CpuOpCode(code: 0x7B, op: CpuInstructionSet.jpo),
    CpuOpCode(code: 0x7C, op: CpuInstructionSet.jl),
    CpuOpCode(code: 0x7D, op: CpuInstructionSet.jge),
    CpuOpCode(code: 0x7E, op: CpuInstructionSet.jle),
    CpuOpCode(code: 0x7F, op: CpuInstructionSet.jg),
    CpuOpCode(code: 0x80, subCode: 0x00, op: CpuInstructionSet.add),
    CpuOpCode(code: 0x80, subCode: 0x01, op: CpuInstructionSet.or),
    CpuOpCode(code: 0x80, subCode: 0x02, op: CpuInstructionSet.adc),
    CpuOpCode(code: 0x80, subCode: 0x03, op: CpuInstructionSet.sbb),
    CpuOpCode(code: 0x80, subCode: 0x04, op: CpuInstructionSet.and),
    CpuOpCode(code: 0x80, subCode: 0x05, op: CpuInstructionSet.sub),
    CpuOpCode(code: 0x80, subCode: 0x06, op: CpuInstructionSet.xor),
    CpuOpCode(code: 0x80, subCode: 0x07, op: CpuInstructionSet.cmp),
    CpuOpCode(code: 0x81, subCode: 0x00, op: CpuInstructionSet.add),
    CpuOpCode(code: 0x81, subCode: 0x01, op: CpuInstructionSet.or),
    CpuOpCode(code: 0x81, subCode: 0x02, op: CpuInstructionSet.adc),
    CpuOpCode(code: 0x81, subCode: 0x03, op: CpuInstructionSet.sbb),
    CpuOpCode(code: 0x81, subCode: 0x04, op: CpuInstructionSet.and),
    CpuOpCode(code: 0x81, subCode: 0x05, op: CpuInstructionSet.sub),
    CpuOpCode(code: 0x81, subCode: 0x06, op: CpuInstructionSet.xor),
    CpuOpCode(code: 0x81, subCode: 0x07, op: CpuInstructionSet.cmp),
    CpuOpCode(code: 0x82, subCode: 0x00, op: CpuInstructionSet.add),
    // CpuOpCode(code: 0x82, subCode: 0x01, op: CpuInstructionSet.unused),
    CpuOpCode(code: 0x82, subCode: 0x02, op: CpuInstructionSet.adc),
    CpuOpCode(code: 0x82, subCode: 0x03, op: CpuInstructionSet.sbb),
    // CpuOpCode(code: 0x82, subCode: 0x04, op: CpuInstructionSet.unused),
    CpuOpCode(code: 0x82, subCode: 0x05, op: CpuInstructionSet.sub),
    // CpuOpCode(code: 0x82, subCode: 0x06, op: CpuInstructionSet.unused),
    CpuOpCode(code: 0x82, subCode: 0x07, op: CpuInstructionSet.cmp),
    CpuOpCode(code: 0x83, subCode: 0x00, op: CpuInstructionSet.add),
    // CpuOpCode(code: 0x83, subCode: 0x01,op: CpuInstructionSet.unused),
    CpuOpCode(code: 0x83, subCode: 0x02, op: CpuInstructionSet.adc),
    CpuOpCode(code: 0x83, subCode: 0x03, op: CpuInstructionSet.sbb),
    // CpuOpCode(code: 0x83, subCode: 0x04,op: CpuInstructionSet.unused),
    CpuOpCode(code: 0x83, subCode: 0x05, op: CpuInstructionSet.sub),
    // CpuOpCode(code: 0x83, subCode: 0x06,op: CpuInstructionSet.unused),
    CpuOpCode(code: 0x83, subCode: 0x07, op: CpuInstructionSet.cmp),
    CpuOpCode(code: 0x84, op: CpuInstructionSet.test),
    CpuOpCode(code: 0x85, op: CpuInstructionSet.test),
    CpuOpCode(code: 0x86, op: CpuInstructionSet.xchg),
    CpuOpCode(code: 0x87, op: CpuInstructionSet.xchg),
    CpuOpCode(code: 0x88, op: CpuInstructionSet.mov),
    CpuOpCode(code: 0x89, op: CpuInstructionSet.mov),
    CpuOpCode(code: 0x8A, op: CpuInstructionSet.mov),
    CpuOpCode(code: 0x8B, op: CpuInstructionSet.mov),
    CpuOpCode(code: 0x8C, op: CpuInstructionSet.mov),
    // CpuOpCode(code: 0x8C, subCode: 1--b, op: CpuInstructionSet.unused),
    CpuOpCode(code: 0x8D, op: CpuInstructionSet.lea),
    CpuOpCode(code: 0x8E, op: CpuInstructionSet.mov),
    // CpuOpCode(code: 0x8E, subCode: 1--b, op: CpuInstructionSet.unused),
    CpuOpCode(code: 0x8F, subCode: 0x00, op: CpuInstructionSet.pop),
    CpuOpCode(code: 0x90, op: CpuInstructionSet.nop),
    CpuOpCode(code: 0x91, op: CpuInstructionSet.xchg),
    CpuOpCode(code: 0x92, op: CpuInstructionSet.xchg),
    CpuOpCode(code: 0x93, op: CpuInstructionSet.xchg),
    CpuOpCode(code: 0x94, op: CpuInstructionSet.xchg),
    CpuOpCode(code: 0x95, op: CpuInstructionSet.xchg),
    CpuOpCode(code: 0x96, op: CpuInstructionSet.xchg),
    CpuOpCode(code: 0x97, op: CpuInstructionSet.xchg),
    CpuOpCode(code: 0x98, op: CpuInstructionSet.cbw),
    CpuOpCode(code: 0x99, op: CpuInstructionSet.cwd),
    CpuOpCode(code: 0x9A, op: CpuInstructionSet.call),
    CpuOpCode(code: 0x9B, op: CpuInstructionSet.wait),
    CpuOpCode(code: 0x9C, op: CpuInstructionSet.pushf),
    CpuOpCode(code: 0x9D, op: CpuInstructionSet.popf),
    CpuOpCode(code: 0x9E, op: CpuInstructionSet.sahf),
    CpuOpCode(code: 0x9F, op: CpuInstructionSet.lahf),
    CpuOpCode(code: 0xA0, op: CpuInstructionSet.mov),
    CpuOpCode(code: 0xA1, op: CpuInstructionSet.mov),
    CpuOpCode(code: 0xA2, op: CpuInstructionSet.mov),
    CpuOpCode(code: 0xA3, op: CpuInstructionSet.mov),
    CpuOpCode(code: 0xA4, op: CpuInstructionSet.movs),
    CpuOpCode(code: 0xA5, op: CpuInstructionSet.movs),
    CpuOpCode(code: 0xA6, op: CpuInstructionSet.cmps),
    CpuOpCode(code: 0xA7, op: CpuInstructionSet.cmps),
    CpuOpCode(code: 0xA8, op: CpuInstructionSet.test),
    CpuOpCode(code: 0xA9, op: CpuInstructionSet.test),
    CpuOpCode(code: 0xAA, op: CpuInstructionSet.stos),
    CpuOpCode(code: 0xAB, op: CpuInstructionSet.stos),
    CpuOpCode(code: 0xAC, op: CpuInstructionSet.lods),
    CpuOpCode(code: 0xAD, op: CpuInstructionSet.lods),
    CpuOpCode(code: 0xAE, op: CpuInstructionSet.scas),
    CpuOpCode(code: 0xAF, op: CpuInstructionSet.scas),
    CpuOpCode(code: 0xB0, op: CpuInstructionSet.mov),
    CpuOpCode(code: 0xB1, op: CpuInstructionSet.mov),
    CpuOpCode(code: 0xB2, op: CpuInstructionSet.mov),
    CpuOpCode(code: 0xB3, op: CpuInstructionSet.mov),
    CpuOpCode(code: 0xB4, op: CpuInstructionSet.mov),
    CpuOpCode(code: 0xB5, op: CpuInstructionSet.mov),
    CpuOpCode(code: 0xB6, op: CpuInstructionSet.mov),
    CpuOpCode(code: 0xB7, op: CpuInstructionSet.mov),
    CpuOpCode(code: 0xB8, op: CpuInstructionSet.mov),
    CpuOpCode(code: 0xB9, op: CpuInstructionSet.mov),
    CpuOpCode(code: 0xBA, op: CpuInstructionSet.mov),
    CpuOpCode(code: 0xBB, op: CpuInstructionSet.mov),
    CpuOpCode(code: 0xBC, op: CpuInstructionSet.mov),
    CpuOpCode(code: 0xBD, op: CpuInstructionSet.mov),
    CpuOpCode(code: 0xBE, op: CpuInstructionSet.mov),
    CpuOpCode(code: 0xBF, op: CpuInstructionSet.mov),
    // CpuOpCode(code: 0xC0, op: CpuInstructionSet.unused),
    // CpuOpCode(code: 0xC1, op: CpuInstructionSet.unused),
    CpuOpCode(code: 0xC2, op: CpuInstructionSet.ret),
    CpuOpCode(code: 0xC3, op: CpuInstructionSet.ret),
    CpuOpCode(code: 0xC4, op: CpuInstructionSet.les),
    CpuOpCode(code: 0xC5, op: CpuInstructionSet.lds),
    CpuOpCode(code: 0xC6, subCode: 0x00, op: CpuInstructionSet.mov),
    CpuOpCode(code: 0xC7, subCode: 0x00, op: CpuInstructionSet.mov),
    // CpuOpCode(code: 0xC8, op: CpuInstructionSet.unused),
    // CpuOpCode(code: 0xC9, op: CpuInstructionSet.unused),
    CpuOpCode(code: 0xCA, op: CpuInstructionSet.ret),
    CpuOpCode(code: 0xCB, op: CpuInstructionSet.ret),
    CpuOpCode(code: 0xCC, op: CpuInstructionSet.int),
    CpuOpCode(code: 0xCD, op: CpuInstructionSet.int),
    CpuOpCode(code: 0xCE, op: CpuInstructionSet.into),
    CpuOpCode(code: 0xCF, op: CpuInstructionSet.iret),
    CpuOpCode(code: 0xD0, subCode: 0x00, op: CpuInstructionSet.rol),
    CpuOpCode(code: 0xD0, subCode: 0x01, op: CpuInstructionSet.ror),
    CpuOpCode(code: 0xD0, subCode: 0x02, op: CpuInstructionSet.rcl),
    CpuOpCode(code: 0xD0, subCode: 0x03, op: CpuInstructionSet.rcr),
    CpuOpCode(code: 0xD0, subCode: 0x04, op: CpuInstructionSet.shl),
    CpuOpCode(code: 0xD0, subCode: 0x05, op: CpuInstructionSet.shr),
    // CpuOpCode(code: 0xD0, subCode: 0x06, op: CpuInstructionSet.unused),
    CpuOpCode(code: 0xD0, subCode: 0x07, op: CpuInstructionSet.sar),
    CpuOpCode(code: 0xD1, subCode: 0x00, op: CpuInstructionSet.rol),
    CpuOpCode(code: 0xD1, subCode: 0x01, op: CpuInstructionSet.ror),
    CpuOpCode(code: 0xD1, subCode: 0x02, op: CpuInstructionSet.rcl),
    CpuOpCode(code: 0xD1, subCode: 0x03, op: CpuInstructionSet.rcr),
    CpuOpCode(code: 0xD1, subCode: 0x04, op: CpuInstructionSet.shl),
    CpuOpCode(code: 0xD1, subCode: 0x05, op: CpuInstructionSet.shr),
    // CpuOpCode(code: 0xD1, subCode: 0x06, op: CpuInstructionSet.unused),
    CpuOpCode(code: 0xD1, subCode: 0x07, op: CpuInstructionSet.sar),
    CpuOpCode(code: 0xD2, subCode: 0x00, op: CpuInstructionSet.rol),
    CpuOpCode(code: 0xD2, subCode: 0x01, op: CpuInstructionSet.ror),
    CpuOpCode(code: 0xD2, subCode: 0x02, op: CpuInstructionSet.rcl),
    CpuOpCode(code: 0xD2, subCode: 0x03, op: CpuInstructionSet.rcr),
    CpuOpCode(code: 0xD2, subCode: 0x04, op: CpuInstructionSet.shl),
    CpuOpCode(code: 0xD2, subCode: 0x05, op: CpuInstructionSet.shr),
    // CpuOpCode(code: 0xD2, subCode: 0x06, op: CpuInstructionSet.unused),
    CpuOpCode(code: 0xD2, subCode: 0x07, op: CpuInstructionSet.sar),
    CpuOpCode(code: 0xD3, subCode: 0x00, op: CpuInstructionSet.rol),
    CpuOpCode(code: 0xD3, subCode: 0x01, op: CpuInstructionSet.ror),
    CpuOpCode(code: 0xD3, subCode: 0x02, op: CpuInstructionSet.rcl),
    CpuOpCode(code: 0xD3, subCode: 0x03, op: CpuInstructionSet.rcr),
    CpuOpCode(code: 0xD3, subCode: 0x04, op: CpuInstructionSet.shl),
    CpuOpCode(code: 0xD3, subCode: 0x05, op: CpuInstructionSet.shr),
    // CpuOpCode(code: 0xD3, subCode: 0x06, op: CpuInstructionSet.unused),
    CpuOpCode(code: 0xD3, subCode: 0x07, op: CpuInstructionSet.sar),
    CpuOpCode(code: 0xD4, op: CpuInstructionSet.aam),
    CpuOpCode(code: 0xD5, op: CpuInstructionSet.aad),
    // CpuOpCode(code: 0xD6, op: CpuInstructionSet.unused),
    CpuOpCode(code: 0xD7, op: CpuInstructionSet.xlat),
    // CpuOpCode(code: 0xD8, op: CpuInstructionSet.esc),
    // CpuOpCode(code: 0xD9, op: CpuInstructionSet.esc),
    // CpuOpCode(code: 0xDA, op: CpuInstructionSet.esc),
    // CpuOpCode(code: 0xDB, op: CpuInstructionSet.esc),
    // CpuOpCode(code: 0xDC, op: CpuInstructionSet.esc),
    // CpuOpCode(code: 0xDD, op: CpuInstructionSet.esc),
    // CpuOpCode(code: 0xDE, op: CpuInstructionSet.esc),
    // CpuOpCode(code: 0xDF, op: CpuInstructionSet.unknown),
    CpuOpCode(code: 0xE0, op: CpuInstructionSet.loopnz),
    CpuOpCode(code: 0xE1, op: CpuInstructionSet.loopz),
    CpuOpCode(code: 0xE2, op: CpuInstructionSet.loop),
    CpuOpCode(code: 0xE3, op: CpuInstructionSet.jcxz),
    CpuOpCode(code: 0xE4, op: CpuInstructionSet.inOp),
    CpuOpCode(code: 0xE5, op: CpuInstructionSet.inOp),
    CpuOpCode(code: 0xE6, op: CpuInstructionSet.out),
    CpuOpCode(code: 0xE7, op: CpuInstructionSet.out),
    CpuOpCode(code: 0xE8, op: CpuInstructionSet.call),
    CpuOpCode(code: 0xE9, op: CpuInstructionSet.jmp),
    CpuOpCode(code: 0xEA, op: CpuInstructionSet.jmp),
    CpuOpCode(code: 0xEB, op: CpuInstructionSet.jmp),
    CpuOpCode(code: 0xEC, op: CpuInstructionSet.inOp),
    CpuOpCode(code: 0xED, op: CpuInstructionSet.inOp),
    CpuOpCode(code: 0xEE, op: CpuInstructionSet.out),
    CpuOpCode(code: 0xEF, op: CpuInstructionSet.out),
    CpuOpCode(code: 0xF0, op: CpuInstructionSet.prefix),
    // CpuOpCode(code: 0xF1, op: CpuInstructionSet.unused),
    CpuOpCode(code: 0xF2, op: CpuInstructionSet.repnz),
    CpuOpCode(code: 0xF3, op: CpuInstructionSet.repz),
    CpuOpCode(code: 0xF4, op: CpuInstructionSet.hlt),
    CpuOpCode(code: 0xF5, op: CpuInstructionSet.cmc),
    CpuOpCode(code: 0xF6, subCode: 0x00, op: CpuInstructionSet.test),
    // CpuOpCode(code: 0xF6, subCode: 0x01, op: CpuInstructionSet.unused),
    CpuOpCode(code: 0xF6, subCode: 0x02, op: CpuInstructionSet.not),
    CpuOpCode(code: 0xF6, subCode: 0x03, op: CpuInstructionSet.neg),
    CpuOpCode(code: 0xF6, subCode: 0x04, op: CpuInstructionSet.mul),
    CpuOpCode(code: 0xF6, subCode: 0x05, op: CpuInstructionSet.imul),
    CpuOpCode(code: 0xF6, subCode: 0x06, op: CpuInstructionSet.div),
    CpuOpCode(code: 0xF6, subCode: 0x07, op: CpuInstructionSet.idiv),
    CpuOpCode(code: 0xF7, subCode: 0x00, op: CpuInstructionSet.test),
    // CpuOpCode(code: 0xF7, subCode: 0x01, op: CpuInstructionSet.unused),
    CpuOpCode(code: 0xF7, subCode: 0x02, op: CpuInstructionSet.not),
    CpuOpCode(code: 0xF7, subCode: 0x03, op: CpuInstructionSet.neg),
    CpuOpCode(code: 0xF7, subCode: 0x04, op: CpuInstructionSet.mul),
    CpuOpCode(code: 0xF7, subCode: 0x05, op: CpuInstructionSet.imul),
    CpuOpCode(code: 0xF7, subCode: 0x06, op: CpuInstructionSet.div),
    CpuOpCode(code: 0xF7, subCode: 0x07, op: CpuInstructionSet.idiv),
    CpuOpCode(code: 0xF8, op: CpuInstructionSet.clc),
    CpuOpCode(code: 0xF9, op: CpuInstructionSet.stc),
    CpuOpCode(code: 0xFA, op: CpuInstructionSet.cli),
    CpuOpCode(code: 0xFB, op: CpuInstructionSet.sti),
    CpuOpCode(code: 0xFC, op: CpuInstructionSet.cld),
    CpuOpCode(code: 0xFD, op: CpuInstructionSet.std),
    CpuOpCode(code: 0xFE, subCode: 0x00, op: CpuInstructionSet.inc),
    CpuOpCode(code: 0xFE, subCode: 0x01, op: CpuInstructionSet.dec),
    // CpuOpCode(code: 0xFE, subCode: 0x02, op: CpuInstructionSet.unused),
    // CpuOpCode(code: 0xFE, subCode: 0x03, op: CpuInstructionSet.unused),
    // CpuOpCode(code: 0xFE, subCode: 0x04, op: CpuInstructionSet.unused),
    // CpuOpCode(code: 0xFE, subCode: 0x05, op: CpuInstructionSet.unused),
    // CpuOpCode(code: 0xFE, subCode: 0x06, op: CpuInstructionSet.unused),
    // CpuOpCode(code: 0xFE, subCode: 0x07, op: CpuInstructionSet.unused),
    CpuOpCode(code: 0xFF, subCode: 0x00, op: CpuInstructionSet.inc),
    CpuOpCode(code: 0xFF, subCode: 0x01, op: CpuInstructionSet.dec),
    CpuOpCode(code: 0xFF, subCode: 0x02, op: CpuInstructionSet.call),
    CpuOpCode(code: 0xFF, subCode: 0x03, op: CpuInstructionSet.call),
    CpuOpCode(code: 0xFF, subCode: 0x04, op: CpuInstructionSet.jmp),
    CpuOpCode(code: 0xFF, subCode: 0x05, op: CpuInstructionSet.jmp),
    CpuOpCode(code: 0xFF, subCode: 0x06, op: CpuInstructionSet.push),
    // CpuOpCode(code: 0xFF, subCode: 0x07, op: CpuInstructionSet.unused),
  ];
}
